### ISSUE TITLE
Sound missing

### ISSUE THREAD

**Issue by theCALiC0** [minecraft-cursed-legacy/Cursed-Legacy-API#24]
I'm not quite sure what is causing it, but with API installed, no sound. Without it, I get sound again.

**Comment by valoeghese** [comment]
Likely related to our sound mixins

**Comment by valoeghese** [comment]
Sound works in dev, but from this error it probably breaks in prod...

**Comment by valoeghese** [comment]
![image](https://user-images.githubusercontent.com/46117728/116463553-4edd0d00-a8c7-11eb-8a31-f336732baaa1.png)
We will hopefully finally be seeing a fix for this. 👍

**Comment by valoeghese** [comment]
Cursed Legacy Installer 1.1.0 will fix that once we upload it (it's an installer issue, not an api issue)
