### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by TheGlitch76** [minecraft-cursed-legacy/Cursed-Legacy-API#3]
Fix or remove.

**Comment by Ueaj-Kerman** [comment]
:yotefuckinhaw:

**Comment by CoolMineman** [comment]
should be fixed now

**Comment by CoolMineman** [comment]
can this still be reproduced?

**Comment by TheGlitch76** [comment]
no that was a meme but glad you somehow found an error

**Comment by Ueaj-Kerman** [comment]
![ioa](https://user-images.githubusercontent.com/28693059/81721433-78e2b880-9445-11ea-8794-4866b5140be3.png)
