### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by CoolMineman** [minecraft-cursed-legacy/Cursed-Legacy-API#4]
Add the ability to run the tests or make it clear how to run them.

**Comment by valoeghese** [comment]
In eclipse they are run just by using the run configs

**Comment by valoeghese** [comment]
how are tests run on idea? I don't use that ide for modding so I don't know myself.

**Comment by valoeghese** [comment]
On IDEA just change it to be built the normal way instead of using gronk I think
